---
title: "TestVersionThesis"
params:
  viridis_palette: viridis
output:
  html_document:
    highlighter: null
    theme: "flatly"
    code_download: TRUE
    toc: true
    toc_float: true
    code_folding: "hide"
    keep_md: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, results='asis'}
library(haven)
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
library(knitr)
library(stargazer)
library(qwraps2)
library(summarytools)
library(AER)
options(qwraps2_markup = "markdown")
```

## R Markdown

#### TABLE 1 - SUMMARY STATISTICS

```{r, results="asis", warning=FALSE}

# Einlesen der Stata-Daten
stata_data <- read_dta("~/GitHub/BA/thesis_code_rep/thesis_code_rep/kz_demandelasts_aer08.dta")

# FunctionTable1 - Übersicht und Kontrolle des Datensatzes
testfunction <- function(stata_data1){
  list("Panel A: Experimental variables" =
         list("Interest rate" = ~ mean_sd(stata_data1$offer4)),
         list("Dynamic repayment incentive" = ~ mean_sd(stata_data1$yearlong)),
         list("Example loan term = 4 months" = ~ mean_sd(stata_data1$termshown4, na_rm = TRUE)),
         list("Example loan term = 6 months" = ~ mean_sd(stata_data1$termshown6, na_rm = TRUE)),
         list("Example loan term = 12 months" = ~ mean_sd(stata_data1$termshown12, na_rm =TRUE)),
         list("Borrowed" = ~ mean_sd(stata_data1$tookup)),
         list("Applied" = ~ mean_sd(stata_data1$applied)),
         list("Loan size" = ~ mean_sd(stata_data1$loansize)),
       "Panel B: Demographic characteristics" =
         list("Female" = ~ mean_sd(stata_data1$female)),
         list("Married" = ~ mean_sd(stata_data1$married, na_rm = TRUE)),
         list("Age" = ~ mean_sd(stata_data1$age)),
         list("More educated" = ~ mean_sd(stata_data1$edhi)),
         list("Rural" = ~ mean_sd(stata_data1$rural)),
         list("Number of dependents" = ~ mean_sd(stata_data1$dependants, na_rm = TRUE)),
         list("Gross monthly income (000s of rand)" = ~ mean_sd(stata_data1$grossincome, na_rm = TRUE)),
         list("Number of loans with the lender" = ~ mean_sd(stata_data1$trcount, na_rm = TRUE))
  )
}


# Spalte1 - All
all_data <- testfunction(stata_data)
summary_all <- summary_table(stata_data, all_data)

# Spalte2 - Applied
applied_data <- stata_data %>% filter(applied == 1)
applied_list <- testfunction(applied_data) 
summary_applied <- summary_table(applied_data, applied_list)

# Spalte3 - Borrowed
borrowed_data <- stata_data %>% filter(tookup == 1)
borrowed_list <- testfunction(borrowed_data) 
summary_borrowed <- summary_table(borrowed_data, borrowed_list)

# Spalte4 - Eligible for maturity suggestion randomizition
maturity_data <- stata_data %>% filter(onetermshown == 1)
maturity_list <- testfunction(maturity_data) 
summary_maturity <- summary_table(maturity_data, maturity_list)

# Zusammenfassen der Listen
summary <- cbind(summary_all, summary_applied, summary_borrowed, summary_maturity)
summary


```


```{r, warning=FALSE, results='asis'}

table1_1 <- descr(stata_data, stats = c("mean", "sd"), transpose = TRUE, headings = FALSE)
table1_2 <- descr(filter(stata_data,applied == 1), stats = c("mean", "sd"), transpose = TRUE, headings = FALSE)

# Alternative - was ist besser?

```


#### TABLE 2 - EXPERIMENTAL VALIDATION REGRESSIONS

```{r, warning=FALSE, results='asis'}

# Table 2 - Experimetal validation Regressions
stata_data$lnitcscore[is.na(stata_data$lnitcscore)] <- 0
stata_data$lnappscore[is.na(stata_data$lnappscore)] <- 0
stata_data$lntrcount[is.na(stata_data$lntrcount)] <- 0


# Regression kürzt viele Werte raus, daher NAs = 0?

reg2_1 <- lm(offer4 ~ dormancy + lntrcount + female + dependants + married + lnage + rural + edhi + lnitcscore + itcany + lnappscore, data=stata_data)

# Ergebnis nicht komplett richtig, woran liegt es? Falsch regressiert?

# teilweise inkorrekte Werte, was ist mit itczero(Wert deutlich zu groß) ?

reg2_2 <- glm(tookup_afterdead_enforced ~ offer4, family = binomial(link = "probit"), data=stata_data)

stata_data_reg3 <- stata_data %>% filter(applied == 1)
reg2_3 <- glm(rejected ~ offer4, family = binomial(link = "probit"), data=stata_data_reg3)

stargazer(reg2_1, reg2_2, reg2_3, type="html", header=FALSE)

```


#### TABLE 3 - THE EXTENSIVE MARGIN: PRICE SENSITIVES OF LOAN TAKE-UP


```{r, warning=FALSE, results='asis'}

reg3_1 <- lm(applied ~ offer4, data=filter(stata_data, normrate_less == 1))

reg3_2 <- lm(applied ~ normrate_more, data=stata_data)

reg3_3 <- lm(applied ~ offer4, data=filter(stata_data, normrate_less == 0))

reg3_4 <- lm(tookup_outside_only ~ offer4, data = filter(stata_data, normrate_less == 1))

reg3_5 <- lm(tookup_outside_only ~ normrate_more, data = stata_data)

reg3_6 <- lm(tookup_outside_only ~ offer4, data = filter(stata_data, normrate_less == 0))

reg3_7 <- lm(tookup_afterdead_enforced ~ offer4, data=filter(stata_data, normrate_less == 1))

reg3_8 <- lm(tookup_afterdead_enforced ~ normrate_more, data = stata_data)

reg3_9 <- lm(tookup_afterdead_enforced ~ offer4, data = filter(stata_data, normrate_less == 0))

stargazer(reg3_1, reg3_2, reg3_3, reg3_4, reg3_5, reg3_6, reg3_7, reg3_8, reg3_9, type="html", header = FALSE)

```

#### TABLE 4 - PRICE SENSITIVITIES OF LOAN SIZE

```{r, warning=FALSE, results='asis'}

# Dataset -> r(interest rate) = rc (contract rate) -> offer4 = final4, normrate_less == 1
# Conditional on borrowing? -> tookup
# Additional controls? + Branch fixed effects? -> grossincome != 0
# Additional controls? -> ???
# Branch fixed effects? -> ???

reg4_1 <- lm(loansize ~ offer4, data = filter(stata_data, offer4==final4, normrate_less==1))

reg4_2 <- lm(loansize ~ offer4, data = filter(stata_data, offer4==final4, normrate_less==1, grossincome!=0))

reg4_3 <- lm(loansize ~ offer4, data = filter(stata_data, offer4==final4, normrate_less==1, tookup==1))

reg4_4 <- lm(loansize ~ offer4, data = filter(stata_data, offer4==final4, normrate_less==1, tookup==1))

reg4_5 <- tobit(loansize ~ offer4, data = filter(stata_data, offer4==final4, normrate_less==1, tookup==1))

reg4_6 <- lm(lnloansize ~ lnoffer4, data = filter(stata_data, offer4==final4, tookup==1, normrate_less==1))

reg4_7 <- lm(lnloansize ~ lnoffer4, data = filter(stata_data, offer4==final4, tookup==1, normrate_less==1, grossincome!=0))

reg4_8 <- tobit(lnloansize ~ lnoffer4, data = filter(stata_data, offer4==final4, tookup==1, normrate_less==1, grossincome!=0))


stargazer(reg4_1, reg4_2, reg4_3, reg4_4, reg4_5, reg4_6, reg4_7, reg4_8, type="html", header = FALSE)


```

##### TABLE 5 - GROSS REVENUE AND REPAYMENT SENSITIVITIES TO INTEREST RATES

```{r, warning=FALSE, results='asis'}

reg5_1 <- lm(grossinterest ~ offer4, data = filter(stata_data, offer4==final4, normrate_less==1))

reg5_2 <- lm(pstdue_average ~ offer4,data = filter(stata_data, offer4==final4, normrate_less==1, tookup==1))

reg5_3 <- tobit(pstdue_average ~ offer4, data = filter(stata_data, offer4==final4, normrate_less==1, tookup==1))


stargazer(reg5_1, reg5_2, reg5_3, type="html",align=TRUE, dep.var.labels=c("Gross interest revenue","Average past due", "Average past due"), covariate.labels=c("interest rate in pp terms (e.g., 8.2)"),no.space=TRUE)

```

#### TABLE 6 - PRICE SENSITIVITY OF LOAN SIZE FOR GROUPS ASSUMED MOST LIKELY TO READ THE SOLICIATION

```{r, warning=FALSE, results='asis'}

```

